// SPORTLAB V11.8.2 — Shared server snapshot bootstrap.
// The snapshot is generated by GitHub Actions and deployed with GitHub Pages.
const MAX_STALE_MS = 72 * 60 * 60 * 1000;
const SNAPSHOT_URL = "./data/server-snapshot.json";

export async function readServerSportsSnapshot({ fetchImpl = globalThis.fetch } = {}) {
  if (typeof fetchImpl !== "function") return null;
  try {
    const response = await fetchImpl(SNAPSHOT_URL, { cache: "no-store", headers: { Accept: "application/json" } });
    if (!response?.ok) return null;
    const snapshot = await response.json();
    if (!snapshot || Number(snapshot.schemaVersion) !== 1 || !snapshot.generatedAt || !snapshot.sports) return null;
    const generatedAtMs = Date.parse(snapshot.generatedAt);
    const ageMs = Date.now() - generatedAtMs;
    if (!Number.isFinite(ageMs) || ageMs < 0 || ageMs > MAX_STALE_MS) return null;
    return { ...snapshot, ageMs };
  } catch (error) {
    console.warn("[ServerSportsSnapshot] Lecture impossible", error);
    return null;
  }
}

export function serverPayloadForDisplay(snapshot, kind) {
  const payload = snapshot?.sports?.[kind];
  if (!payload || payload?.meta?.error === true || !Array.isArray(payload?.matches)) return null;
  return {
    ...payload,
    meta: {
      ...(payload.meta || {}),
      loading: false,
      serverSnapshot: true,
      snapshot: true,
      snapshotSavedAt: snapshot.generatedAt,
      snapshotAgeMs: snapshot.ageMs,
      refreshingInBackground: true
    }
  };
}
